import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <footer className="footer footer-center p-4 bg-base-200 text-base-content">
        <aside>
          <p>Copyright © 2023 - All right reserved by Modakoda</p>
        </aside>
      </footer>
      </body>
    </html>
  );
}
